image: archlinux
packages:
  - nodejs
  - npm
  - rsync
sources:
  - https://github.com/SirCmpwn/receptor
environment:
  deploy: synapse@synapse-bt.org
secrets:
  - 7ebab768-e5e4-4c9d-ba57-ec41a72c5665
tasks:
  - setup: |
      cd receptor
      npm install
  - build: |
      cd receptor
      npm run build:production
  - deploy: |
      cd receptor
      sshopts="-o StrictHostKeyChecking=no"
      rsync --rsh="ssh $sshopts" -rP index.html ${deploy}:/var/www/web.synapse-bt.org/
      rsync --rsh="ssh $sshopts" -rP dist ${deploy}:/var/www/web.synapse-bt.org/
